/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarIndexRouteImport } from './routes/buscar.index'
import { Route as ProSlugRouteImport } from './routes/pro.$slug'
import { Route as DemandasNovaRouteImport } from './routes/demandas.nova'
import { Route as AvaliarTokenRouteImport } from './routes/avaliar.$token'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedModeracaoRouteImport } from './routes/_authenticated/moderacao'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as BuscarCategoriaRegiaoRouteImport } from './routes/buscar.$categoria.$regiao'
import { Route as AuthenticatedPainelPropostasRouteImport } from './routes/_authenticated/painel.propostas'
import { Route as AuthenticatedPainelPipelineRouteImport } from './routes/_authenticated/painel.pipeline'
import { Route as AuthenticatedPainelPerfilRouteImport } from './routes/_authenticated/painel.perfil'
import { Route as AuthenticatedPainelDestaqueRouteImport } from './routes/_authenticated/painel.destaque'
import { Route as AuthenticatedPainelDemandasRouteImport } from './routes/_authenticated/painel.demandas'
import { Route as AuthenticatedPainelCrmRouteImport } from './routes/_authenticated/painel.crm'
import { Route as AuthenticatedPainelAvaliacoesRouteImport } from './routes/_authenticated/painel.avaliacoes'
import { Route as AuthenticatedPainelAssinaturaRouteImport } from './routes/_authenticated/painel.assinatura'
import { Route as AuthenticatedPainelAgendaRouteImport } from './routes/_authenticated/painel.agenda'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarIndexRoute = BuscarIndexRouteImport.update({
  id: '/buscar/',
  path: '/buscar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugRoute = ProSlugRouteImport.update({
  id: '/pro/$slug',
  path: '/pro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandasNovaRoute = DemandasNovaRouteImport.update({
  id: '/demandas/nova',
  path: '/demandas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarTokenRoute = AvaliarTokenRouteImport.update({
  id: '/avaliar/$token',
  path: '/avaliar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModeracaoRoute = AuthenticatedModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const BuscarCategoriaRegiaoRoute = BuscarCategoriaRegiaoRouteImport.update({
  id: '/buscar/$categoria/$regiao',
  path: '/buscar/$categoria/$regiao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelPropostasRoute =
  AuthenticatedPainelPropostasRouteImport.update({
    id: '/propostas',
    path: '/propostas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPipelineRoute =
  AuthenticatedPainelPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPerfilRoute =
  AuthenticatedPainelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDestaqueRoute =
  AuthenticatedPainelDestaqueRouteImport.update({
    id: '/destaque',
    path: '/destaque',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDemandasRoute =
  AuthenticatedPainelDemandasRouteImport.update({
    id: '/demandas',
    path: '/demandas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCrmRoute = AuthenticatedPainelCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelAvaliacoesRoute =
  AuthenticatedPainelAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAssinaturaRoute =
  AuthenticatedPainelAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAgendaRoute =
  AuthenticatedPainelAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/demandas/nova': typeof DemandasNovaRoute
  '/pro/$slug': typeof ProSlugRoute
  '/buscar/': typeof BuscarIndexRoute
  '/painel/agenda': typeof AuthenticatedPainelAgendaRoute
  '/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/crm': typeof AuthenticatedPainelCrmRoute
  '/painel/demandas': typeof AuthenticatedPainelDemandasRoute
  '/painel/destaque': typeof AuthenticatedPainelDestaqueRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/painel/pipeline': typeof AuthenticatedPainelPipelineRoute
  '/painel/propostas': typeof AuthenticatedPainelPropostasRoute
  '/buscar/$categoria/$regiao': typeof BuscarCategoriaRegiaoRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/demandas/nova': typeof DemandasNovaRoute
  '/pro/$slug': typeof ProSlugRoute
  '/buscar': typeof BuscarIndexRoute
  '/painel/agenda': typeof AuthenticatedPainelAgendaRoute
  '/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/painel/crm': typeof AuthenticatedPainelCrmRoute
  '/painel/demandas': typeof AuthenticatedPainelDemandasRoute
  '/painel/destaque': typeof AuthenticatedPainelDestaqueRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/painel/pipeline': typeof AuthenticatedPainelPipelineRoute
  '/painel/propostas': typeof AuthenticatedPainelPropostasRoute
  '/buscar/$categoria/$regiao': typeof BuscarCategoriaRegiaoRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/moderacao': typeof AuthenticatedModeracaoRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/avaliar/$token': typeof AvaliarTokenRoute
  '/demandas/nova': typeof DemandasNovaRoute
  '/pro/$slug': typeof ProSlugRoute
  '/buscar/': typeof BuscarIndexRoute
  '/_authenticated/painel/agenda': typeof AuthenticatedPainelAgendaRoute
  '/_authenticated/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/_authenticated/painel/avaliacoes': typeof AuthenticatedPainelAvaliacoesRoute
  '/_authenticated/painel/crm': typeof AuthenticatedPainelCrmRoute
  '/_authenticated/painel/demandas': typeof AuthenticatedPainelDemandasRoute
  '/_authenticated/painel/destaque': typeof AuthenticatedPainelDestaqueRoute
  '/_authenticated/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/_authenticated/painel/pipeline': typeof AuthenticatedPainelPipelineRoute
  '/_authenticated/painel/propostas': typeof AuthenticatedPainelPropostasRoute
  '/buscar/$categoria/$regiao': typeof BuscarCategoriaRegiaoRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/moderacao'
    | '/onboarding'
    | '/painel'
    | '/avaliar/$token'
    | '/demandas/nova'
    | '/pro/$slug'
    | '/buscar/'
    | '/painel/agenda'
    | '/painel/assinatura'
    | '/painel/avaliacoes'
    | '/painel/crm'
    | '/painel/demandas'
    | '/painel/destaque'
    | '/painel/perfil'
    | '/painel/pipeline'
    | '/painel/propostas'
    | '/buscar/$categoria/$regiao'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/moderacao'
    | '/onboarding'
    | '/avaliar/$token'
    | '/demandas/nova'
    | '/pro/$slug'
    | '/buscar'
    | '/painel/agenda'
    | '/painel/assinatura'
    | '/painel/avaliacoes'
    | '/painel/crm'
    | '/painel/demandas'
    | '/painel/destaque'
    | '/painel/perfil'
    | '/painel/pipeline'
    | '/painel/propostas'
    | '/buscar/$categoria/$regiao'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/moderacao'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/avaliar/$token'
    | '/demandas/nova'
    | '/pro/$slug'
    | '/buscar/'
    | '/_authenticated/painel/agenda'
    | '/_authenticated/painel/assinatura'
    | '/_authenticated/painel/avaliacoes'
    | '/_authenticated/painel/crm'
    | '/_authenticated/painel/demandas'
    | '/_authenticated/painel/destaque'
    | '/_authenticated/painel/perfil'
    | '/_authenticated/painel/pipeline'
    | '/_authenticated/painel/propostas'
    | '/buscar/$categoria/$regiao'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  AvaliarTokenRoute: typeof AvaliarTokenRoute
  DemandasNovaRoute: typeof DemandasNovaRoute
  ProSlugRoute: typeof ProSlugRoute
  BuscarIndexRoute: typeof BuscarIndexRoute
  BuscarCategoriaRegiaoRoute: typeof BuscarCategoriaRegiaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar/': {
      id: '/buscar/'
      path: '/buscar'
      fullPath: '/buscar/'
      preLoaderRoute: typeof BuscarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug': {
      id: '/pro/$slug'
      path: '/pro/$slug'
      fullPath: '/pro/$slug'
      preLoaderRoute: typeof ProSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandas/nova': {
      id: '/demandas/nova'
      path: '/demandas/nova'
      fullPath: '/demandas/nova'
      preLoaderRoute: typeof DemandasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar/$token': {
      id: '/avaliar/$token'
      path: '/avaliar/$token'
      fullPath: '/avaliar/$token'
      preLoaderRoute: typeof AvaliarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderacao': {
      id: '/_authenticated/moderacao'
      path: '/moderacao'
      fullPath: '/moderacao'
      preLoaderRoute: typeof AuthenticatedModeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/buscar/$categoria/$regiao': {
      id: '/buscar/$categoria/$regiao'
      path: '/buscar/$categoria/$regiao'
      fullPath: '/buscar/$categoria/$regiao'
      preLoaderRoute: typeof BuscarCategoriaRegiaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/propostas': {
      id: '/_authenticated/painel/propostas'
      path: '/propostas'
      fullPath: '/painel/propostas'
      preLoaderRoute: typeof AuthenticatedPainelPropostasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pipeline': {
      id: '/_authenticated/painel/pipeline'
      path: '/pipeline'
      fullPath: '/painel/pipeline'
      preLoaderRoute: typeof AuthenticatedPainelPipelineRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/perfil': {
      id: '/_authenticated/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthenticatedPainelPerfilRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/destaque': {
      id: '/_authenticated/painel/destaque'
      path: '/destaque'
      fullPath: '/painel/destaque'
      preLoaderRoute: typeof AuthenticatedPainelDestaqueRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/demandas': {
      id: '/_authenticated/painel/demandas'
      path: '/demandas'
      fullPath: '/painel/demandas'
      preLoaderRoute: typeof AuthenticatedPainelDemandasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/crm': {
      id: '/_authenticated/painel/crm'
      path: '/crm'
      fullPath: '/painel/crm'
      preLoaderRoute: typeof AuthenticatedPainelCrmRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/avaliacoes': {
      id: '/_authenticated/painel/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/painel/avaliacoes'
      preLoaderRoute: typeof AuthenticatedPainelAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/assinatura': {
      id: '/_authenticated/painel/assinatura'
      path: '/assinatura'
      fullPath: '/painel/assinatura'
      preLoaderRoute: typeof AuthenticatedPainelAssinaturaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/agenda': {
      id: '/_authenticated/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof AuthenticatedPainelAgendaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAgendaRoute: typeof AuthenticatedPainelAgendaRoute
  AuthenticatedPainelAssinaturaRoute: typeof AuthenticatedPainelAssinaturaRoute
  AuthenticatedPainelAvaliacoesRoute: typeof AuthenticatedPainelAvaliacoesRoute
  AuthenticatedPainelCrmRoute: typeof AuthenticatedPainelCrmRoute
  AuthenticatedPainelDemandasRoute: typeof AuthenticatedPainelDemandasRoute
  AuthenticatedPainelDestaqueRoute: typeof AuthenticatedPainelDestaqueRoute
  AuthenticatedPainelPerfilRoute: typeof AuthenticatedPainelPerfilRoute
  AuthenticatedPainelPipelineRoute: typeof AuthenticatedPainelPipelineRoute
  AuthenticatedPainelPropostasRoute: typeof AuthenticatedPainelPropostasRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAgendaRoute: AuthenticatedPainelAgendaRoute,
  AuthenticatedPainelAssinaturaRoute: AuthenticatedPainelAssinaturaRoute,
  AuthenticatedPainelAvaliacoesRoute: AuthenticatedPainelAvaliacoesRoute,
  AuthenticatedPainelCrmRoute: AuthenticatedPainelCrmRoute,
  AuthenticatedPainelDemandasRoute: AuthenticatedPainelDemandasRoute,
  AuthenticatedPainelDestaqueRoute: AuthenticatedPainelDestaqueRoute,
  AuthenticatedPainelPerfilRoute: AuthenticatedPainelPerfilRoute,
  AuthenticatedPainelPipelineRoute: AuthenticatedPainelPipelineRoute,
  AuthenticatedPainelPropostasRoute: AuthenticatedPainelPropostasRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedModeracaoRoute: typeof AuthenticatedModeracaoRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedModeracaoRoute: AuthenticatedModeracaoRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  AvaliarTokenRoute: AvaliarTokenRoute,
  DemandasNovaRoute: DemandasNovaRoute,
  ProSlugRoute: ProSlugRoute,
  BuscarIndexRoute: BuscarIndexRoute,
  BuscarCategoriaRegiaoRoute: BuscarCategoriaRegiaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
